version: "3.9"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/blog_development"
      REDIS_URL: redis://redis:6379/1
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}  
    env_file:
      - .env 

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_development
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/blog_development"
      REDIS_URL: "redis://redis:6379/0"
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}  
    env_file:
      - .env  

volumes:
  pg_data:
