default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_development
  username: postgres
  password: password
  host: db
  port: 5432

test:
  <<: *default
  database: blog_test
  username: postgres
  password: password
  host: db
  port: 5432

production:
  <<: *default
  database: blog_production
  username: postgres
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
  host: db
  port: 5432
